modLoader="javafml"
loaderVersion="[45,)"
license="GLGPLv3"
[[mods]] #mandatory
modId="chiselsandbits"
version="${file.jarVersion}"
displayName="Chisels & bits"
authors="OrionOnline, LDTTeam, AlgorithmX2 "
description='''
a mod about Sculpting, Decorating and Aesthetics.

Ported to 1.16.x by the LDTTeam.

Ported to 1.18.x by the SQwatermark.
'''
